services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - 15672:15672
      - 5672:5672

  mysql:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_DATABASE=edosdb'
      - 'MYSQL_USER=admin'
      - 'MYSQL_PASSWORD=123'
      - 'MYSQL_ROOT_PASSWORD=root'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

volumes:
  mysql_data:
